// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1xKsUizM1sGDVUaPTQiBck-B7IMNMP8Q',
    appId: '1:262590802073:web:625cf8baa2dc697227f008',
    messagingSenderId: '262590802073',
    projectId: 'obviously-060924',
    authDomain: 'obviously-060924.firebaseapp.com',
    storageBucket: 'obviously-060924.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2_K3vIWeLlLPnJrfGgCJk4LP_KNmGf6A',
    appId: '1:262590802073:android:5337d12c1cd62bb127f008',
    messagingSenderId: '262590802073',
    projectId: 'obviously-060924',
    storageBucket: 'obviously-060924.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuIV2W1p6SYsVDZZh3EC6s5pV_gS1O1sE',
    appId: '1:262590802073:ios:cab230b0bc8bece627f008',
    messagingSenderId: '262590802073',
    projectId: 'obviously-060924',
    storageBucket: 'obviously-060924.appspot.com',
    iosBundleId: 'com.example.obviouslyTestFinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuIV2W1p6SYsVDZZh3EC6s5pV_gS1O1sE',
    appId: '1:262590802073:ios:cab230b0bc8bece627f008',
    messagingSenderId: '262590802073',
    projectId: 'obviously-060924',
    storageBucket: 'obviously-060924.appspot.com',
    iosBundleId: 'com.example.obviouslyTestFinal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1xKsUizM1sGDVUaPTQiBck-B7IMNMP8Q',
    appId: '1:262590802073:web:e3ff96f37d4db20b27f008',
    messagingSenderId: '262590802073',
    projectId: 'obviously-060924',
    authDomain: 'obviously-060924.firebaseapp.com',
    storageBucket: 'obviously-060924.appspot.com',
  );
}
